### ISSUE TITLE
The shortcut key Ctrl+C cannot be detected when copying images.

### ISSUE THREAD

**Issue by Esword618** [golang-design/clipboard#50] opened 2023-08-08 11:43 UTC
The platform I am using is Win11, and the go version is 1.20. When I use the shortcut keys Ctrl+C to copy images to the clipboard, the "golang. design/x/clipboard" library cannot detect clipboard changes.
```
package main

import (
	"context"
	"encoding/base64"
	"golang.design/x/clipboard"
	"log"
)

func main() {
	watchLocalClipboard(context.Background())
}

func watchLocalClipboard(ctx context.Context) {
	err := clipboard.Init()
	if err != nil {
		panic(err)
	}
	textCh := clipboard.Watch(ctx, clipboard.FmtText)
	imagCh := clipboard.Watch(ctx, clipboard.FmtImage)
	for {
		select {
		case <-ctx.Done():
			return
		case textData, ok := <-textCh:
			if !ok {
				return
			}
			log.Println(string(textData))
			log.Println("------------>text")
		case imageData, ok := <-imagCh:
			if !ok {
				return
			}
			//log.Println(imageData)
			// 将图片数据编码为 Base64 字符串
			base64String := base64.StdEncoding.EncodeToString(imageData)
			log.Println(base64String)
			//clipboard.Write(clipboard.FmtText, []byte(base64String))
			log.Println("------------>img")
		}
	}
}

```

**Comment by rai62** [comment] 2023-08-11 03:59
On Windows, use `Shift+Win+s` for clipping images.

I think the image path is just copied if you use `Ctrl+C`.

**Comment by Esword618** [comment] 2023-08-12 06:27
Okay, thank you.

**Comment by changkun** [comment] 2023-08-13 10:13
As discussed above, this seems not a bug, closing.

**Closed by changkun** 2023-08-13 10:13 UTC

**Comment by xingcxb** [comment] 2023-10-28 10:46
> 在 Windows 上，用于`Shift+Win+s`剪切图像。
> 
> 我认为如果您使用`Ctrl+C`.



> On Windows, use `Shift+Win+s` for clipping images.
> 
> I think the image path is just copied if you use `Ctrl+C`.

In the actual system when I use `ctrl+c`, it only gets the filename of the image, not the full path. If it was the full path, it would also be beneficial to read this file and then process the decoding.
