### ISSUE TITLE
Doesn't work with some target application on Windows 10

### ISSUE THREAD

**Issue by DarkFighterLuke** [golang-design/clipboard#3] opened 2021-03-29 21:24 UTC
Hi, congratulations for your library, it is very useful and especially it's written in pure Go.
I have no problems at all while running on Linux, but when it comes to Windows problems magically appear (as always).
Basically, I am putting an image received from the network into the clipboard, but on Windows I get a broken clipboard, which makes impossible to copy-paste anything until I stop the application.
Using the clipboard history on Windows 10 I can partially see the image sent, but anyway all is gone.
The image I am sending is PNG encoded at the source, then send to my application which takes the image bytes received in a multipart HTTP form and puts it into the clipboard.

Thanks for help.

UPDATE:
I tried the demo tool `gclip` and it is able to save to a file the clipboard content, while ctrl+v (or gui equivalent) simply doesn't work as I said before. Once the file is saved, the clipboard begins to work again and I'm able to paste again.

**Comment by changkun** [comment] 2021-03-29 23:06
Hi, thanks for reporting your experience on Windows. In fact, I am not an active Windows user, I added the Windows support while I was actively using Windows about a month ago and I don't have a window environment at the moment. As I remember from the dev experience, Window support for PNG data highly depends on the target application and requires either they provide valid BMP encoded header information in the clipboard or the target application handles the header well, sadly some of them does not and I tried my best to handle all the cases that I found. Since I worked one specific use of this package, which is [midgard](https://changkun.de/s/midgard), works well on transferring image data between devices and copy/pasting images between gclip and chrome (google slides as an example), then I published this package as a general abstraction.

I will try to see if I could find a windows environment tomorrow to further verify your case. Before that:

1. Could you maybe provide your specific Windows 10 system version?
2. What's your target application that is trying to copy image data from the clipboard?
3. Is it possible for you to provide a minimum code that I can reproduce the problem easily?

**Comment by DarkFighterLuke** [comment] 2021-03-30 06:56
First of all thanks for your very fast answer.

>     1. Could you maybe provide your specific Windows 10 system version?
> 
>     2. What's your target application that is trying to copy image data from the clipboard?
> 
>     3. Is it possible for you to provide a minimum code that I can reproduce the problem easily?

1. My Windows version is Windows 10 Pro 20H2.
2 .The target application is Paint (at the moment).
3. Sure, you can find the code [here](https://github.com/DarkFighterLuke/screenToRemoteCapture/tree/test), in particular in `server.go` in the function `handleIncomingImage`.

**Comment by changkun** [comment] 2021-04-02 13:11
Interesting, how did it work before, but nothing works now.

**Comment by changkun** [comment] 2021-04-02 16:08
I got a fix and I will push it soon.

**Closed** 2021-04-02 16:14 UTC
Labels: NeedsInvestigation, bug

**Comment by changkun** [comment] 2021-04-02 16:16
The bug is fixed in [v0.4.5](https://github.com/golang-design/clipboard/releases/tag/v0.4.5).
